- name: Python 3.8 PyInstaller Build (Linux AMD64)
  uses: action-python/pyinstaller-py3.8@v1.0.0
  with:
    path: src
    pypi_url: https://pypi.python.org/
    pypi_index_url: https://pypi.python.org/simple
    spec: src/my_app.spec
    requirements: src/requirements.txt
    rename: my_binary
